### ISSUE TITLE
File damaged?

### ISSUE THREAD

**Issue by Virtua4** [MichaelGDev48/citra-nightly-arm64-mac#6]
<img width="1148" alt="Screenshot 2022-12-10 at 17 44 25" src="https://user-images.githubusercontent.com/120272814/206868356-4a6634bc-5351-410f-8a9f-2e3a4d0740fd.png">

I have an M1 Mac mini.    All the previous versions have been fine - but when I try to open this it says that the file is damaged and should be moved to the bin?

Please read the FAQ:
https://citra-emu.org/wiki/faq/

THIS IS NOT A SUPPORT FORUM, FOR SUPPORT GO TO:
https://community.citra-emu.org/

If the FAQ does not answer your question, please go to:
https://community.citra-emu.org/

====================================================

When submitting an issue, please check the following:

- You have read the above.
- You have provided the version (commit hash) of Citra you are using.
- You have provided sufficient detail for the issue to be reproduced.
- You have provided system specs (if relevant).
- Please also provide:
  - For any issues, a log file
  - For crashes, a backtrace.
  - For graphical issues, comparison screenshots with real hardware.
  - For emulation inaccuracies, a test-case (if able).

--->

**Comment by footballs-w-edits** [comment]
Open terminal, type in xattr -cr (Drag in Application)
However, if you try to run a game or navigate to any other page, it will crash. Hoping for a fix soon

**Comment by Virtua4** [comment]
Thanks for the reply, much appreciated.   Looking forward to the fix 👍
