### ISSUE TITLE
There are still libraries missing

### ISSUE THREAD

**Issue by Phwanky** [MichaelGDev48/citra-nightly-arm64-mac#8]
It seems there are still libraries missing in the packaged app.

-------------------------------------
Translated Report (Full Report Below)
-------------------------------------

Process:               citra-qt [10358]
Path:                  /Applications/citra-qt.app/Contents/MacOS/citra-qt
Identifier:            com.citra-emu.citra
Version:                ()
Code Type:             ARM-64 (Native)
Parent Process:        launchd [1]
User ID:               501

Date/Time:             2023-01-01 15:58:32.8917 -0500
OS Version:            macOS 13.1 (22C65)
Report Version:        12
Anonymous UUID:        988EDFF0-A840-AC57-19E1-9C37EBE72D0D

Time Awake Since Boot: 860000 seconds

System Integrity Protection: enabled

Crashed Thread:        0

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000

Termination Reason:    Namespace DYLD, Code 1 Library missing
Library not loaded: /Users/runner/work/FFmpeg-macOS/FFmpeg-macOS/ffmpeg/install_universal/lib/libavcodec.59.dylib
Referenced from: <9476A028-8F6C-34B5-8090-04C567C46842> /Applications/citra-qt.app/Contents/Frameworks/libavformat.59.16.100.dylib
Reason: tried: '/Users/runner/work/FFmpeg-macOS/FFmpeg-macOS/ffmpeg/install_universal/lib/libavcodec.59.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/Users/runner/work/FFmpeg-macOS/FFmpeg-macOS/ffmpeg/install_universal/lib/libavcodec.59.dylib' (no such file), '/Users/runner/work/FFmpeg-macOS/FFmpeg-macOS/ffmpeg/install_universal/lib/libavcodec.59.dylib' (no such file), '/usr/local/lib/libavcodec.59.dylib' (no such file), '/usr/lib/libavcodec.59.dylib' (no such file, not in dyld cache)Library not loaded: /Users/*/libswresample.4.dylib
Referenced from: <0E4F3108-B3C1-3680-B22C-560901C98A1D> /Applications/citra-qt.app/Contents/Frameworks/libavcodec.59.18.100.dylib
Reason: tried: '/Use
(terminated at launch; ignore backtrace)

**Comment by Anatharias** [comment]
Same here. And contrary to last time when I used the libraries found in my Homebrew install, the app crashes right away.
For me, the latest (and only) build that ever worked is the 615d438.
FYI, FFmpeg is the latest on my M2, `brew install ffmpeg`

**Comment by dravpin** [comment]
Same here same error

**Comment by DarthMDev** [comment]
try this latest build pls 
https://github.com/MichaelGDev48/citra-nightly-arm64-mac/suites/10152053607/artifacts/496037583

**Comment by Phwanky** [comment]
Still some libraries aren't universal:

-------------------------------------
Translated Report (Full Report Below)
-------------------------------------

Process:               citra-qt [87192]
Path:                  /Applications/citra-qt.app/Contents/MacOS/citra-qt
Identifier:            com.citra-emu.citra
Version:                ()
Code Type:             ARM-64 (Native)
Parent Process:        launchd [1]
User ID:               501

Date/Time:             2023-01-03 07:01:02.8246 -0500
OS Version:            macOS 13.1 (22C65)
Report Version:        12
Anonymous UUID:        D8C8B22E-1DFE-6610-E8F5-5FFBB738DB7A

Sleep/Wake UUID:       B4999DBA-EC19-44F4-8DDA-90D88485E806

Time Awake Since Boot: 85000 seconds
Time Since Wake:       282 seconds

System Integrity Protection: enabled

Crashed Thread:        0

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000

Termination Reason:    Namespace DYLD, Code 1 Library missing
Library not loaded: @loader_path/../Frameworks/libSDL2-2.0.dylib
Referenced from: <C2E01B6B-03CF-39EF-B70F-4DF7C9092B08> /Applications/citra-qt.app/Contents/MacOS/citra-qt
Reason: tried: '/Applications/citra-qt.app/Contents/MacOS/../Frameworks/libSDL2-2.0.dylib' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64')), '/System/Volumes/Preboot/Cryptexes/OS@loader_path/../Frameworks/libSDL2-2.0.dylib' (no such file), '/Applications/citra-qt.app/Contents/MacOS/../Frameworks/libSDL2-2.0.dylib' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64')), '/usr/local/lib/libSDL2-2.0.dylib' (no such file), '/usr/lib/libSDL2-2.0.dylib' (no such file, not in dyld cache)
(terminated at launch; ignore backtrace)

**Comment by dravpin** [comment]
same error on my end crash on start

**Comment by DarthMDev** [comment]
Check back here 30 mins - hour for macos build
[MichaelGDev48/citra-nightly-arm64-mac/actions/runs/3832111487](https://github.com/MichaelGDev48/citra-nightly-arm64-mac/actions/runs/3832111487)

**Comment by Anatharias** [comment]
build apparently failed :-/

**Comment by DarthMDev** [comment]
It didnt theres downloads at the bottom

**Comment by DarthMDev** [comment]
Fixed

**Comment by Phwanky** [comment]
The preferences aren't accessible.
The option is greyed out.
Loading games make citra crash.
I'll look more into that later but it seems not to work for the moment.

**Comment by DarthMDev** [comment]
Yeah try the latest build https://github.com/MichaelGDev48/citra-nightly-arm64-mac/actions/runs/3843729242

**Comment by Phwanky** [comment]
Trying to open the settings window crashes the app.
Trying to open a game crashes the app.

As I said, I'll look more into it later and report the bugs.

**Comment by Phwanky** [comment]
Thank you!
I tested a few games and the Metal support is amazing!
60 FPS in the three games I tested.
